# Generated by Django 4.0 on 2022-03-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='subject',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
