# Generated by Django 4.0 on 2022-03-28 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0006_userinfo_college_name_userinfo_hschool_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='skill',
        ),
    ]
