# Generated by Django 4.0 on 2022-03-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0008_alter_userinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profile_pic',
            field=models.ImageField(upload_to='image/userprofil/'),
        ),
    ]
