# Generated by Django 4.0 on 2022-04-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0011_userinfo_college_document_userinfo_hschool_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='college_document',
            field=models.FileField(upload_to='image/userprofil/'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='hschool_document',
            field=models.FileField(upload_to='image/userprofil/'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='sccs_document',
            field=models.FileField(upload_to='image/userprofil/'),
        ),
    ]
