# Generated by Django 4.0 on 2022-03-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Company_logo',
            field=models.ImageField(upload_to='image/companyLogo/'),
        ),
    ]
