# Generated by Django 4.0 on 2022-04-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0003_alter_company_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateProfileRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Request', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='gender',
        ),
    ]
