# Generated by Django 4.0 on 2022-04-01 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0004_updateprofilerequest_remove_company_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updateprofilerequest',
            old_name='Request',
            new_name='Request_update',
        ),
    ]
