# Generated by Django 4.0 on 2022-04-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0005_rename_request_updateprofilerequest_request_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateprofilerequest',
            name='Request_update',
            field=models.CharField(max_length=50),
        ),
    ]
